name: new release
on: 
  release: 
    types: [created,published,deleted]
jobs:
  log-release-created:    
    runs-on: windows-latest
    steps:
      - name: "Print Release"
        run: |
          echo "::group::Release Info"
          echo "New Release Triggered"
          echo "Event: ${{ github.event.action }}"
          echo "Tag: ${{ github.event.release.tag_name }}"
          echo "::endgroup::"

