name: new release
on: 
  release: 
    types: [created,published]
jobs:
  log-release-created:    
    runs-on: windows-latest
    steps:
      - name: "Print Release"
        run: echo "New Release"

